version: "3.8" 
services: 
  webapp: 
    build: 
      context: "./webapp"

      dockerfile: Dockerfile
  
  database: 
    container_name: postgres
    image: postgres:12.2-alpine
    ports: 
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  db_data: ~
